server:
  port: 8080
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/bookmyshow
    username: bookmyshow
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL9Dialect